### PR TITLE
refactor meet redirects

### PR DESCRIPTION
**Pull request by elbotho**
based on #201

### CODE REVIEW

**Comment by elbotho** [comment]
`url.pathname as keyof typeof meetRedirects` looks a bit hacky.
But since TS does not seem to interpret the `url.pathname in …` part it's the best solution I could find.

**Review by CarolinJaser — APPROVED** [review]
Looks good to me. I think even with the hacky keyof typeof it is better to have it refactored like this in the long run instead of ending up with a large and unwieldy switch block

**Comment by elbotho** [comment]
@kulla as our resident typescript magician, maybe you have to say something about that. Otherwise this can be merged :)

**Comment by kulla** [comment]
> @kulla as our resident typescript magician, maybe you have to say something about that. Otherwise this can be merged :)

See https://github.com/serlo/serlo.org-cloudflare-worker/pull/202/commits/4a4dfc5d4af048976ca190103acc0f4f7e1ce474 Here you use a JS object as a Record instead of an TS object. For a TS object you can only fetch arguments which are already defined (unfortunately the `in` operator is not defined as a type guard yet). With broadening the type of `meetRedirects` to `Record<string, string | undefined>` you say: You can fetch any property (= `string`) of this object and you get `string` or `undefined` as result.

**Pull request merged**
