### PR TITLE
Added redirect for fundraising

### LINKED ISSUE #200: New Redirect /fundraising
New redirect:                        meet.serlo.org/fundraising 
should redirect to:                https://meet.google.com/uus-vjgu-ttr

### PR DESCRIPTION
**Pull request by CarolinJaser**
Closes #200 Sorry Botho for the confusion! Maybe you could take a look at my solution instead?

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
Looks good! 👍 
Self assignment is appreciated, but was a small thing so no worries.

Do you think we should refactor this code to make it a bit more compact in the future?

**Comment by CarolinJaser** [comment]
> Looks good! 👍
> Self assignment is appreciated, but was a small thing so no worries.
> 
> Do you think we should refactor this code to make it a bit more compact in the future?

I saw that both /reviewing and /begleitung redirect to the same url. That does not make sense to me at first glance. Is there a reason for this? And yeah, I think if this list gets any longer, refactoring might be better.

**Comment by elbotho** [comment]
> /reviewing and /begleitung

good question. Might just be an alias, but I have no info on this.

**Comment by kulla** [comment]
> I saw that both /reviewing and /begleitung redirect to the same url. That does not make sense to me at first glance. Is there a reason for this? And yeah, I think if this list gets any longer, refactoring might be better.

Yes, this is intended (was requested by @yolo-bird to have the same url for both redirects since both are used by the same unit)

**Pull request merged**
